### PR TITLE
Make the header sticky

### PR DESCRIPTION
**Pull request by SubxX**
[Issue](https://github.com/Clueless-Community/first-contribution/issues/260)

### CODE REVIEW

**Comment by Rajdip019** [comment]
Please resolve the merge conflicts and update the PR @SubxX

**Comment by SubxX** [comment]
Conflicts resolved @Rajdip019

**Comment by SubxX** [comment]
New conflicts resolved @Rajdip019

**Comment by SubxX** [comment]
https://www.clueless.tech/profile/admin/51792949 @Rajdip019

**Pull request merged**
