### PR TITLE
Transitional underline on hover added

### PR DESCRIPTION
**Pull request by RidhamRj**
reference to #223

### CODE REVIEW

**Comment by RidhamRj** [comment]
@Rajdip019 pls review

**Comment by RidhamRj** [comment]
@nikhil25803

**Comment by RidhamRj** [comment]
https://www.clueless.tech/profile/admin/86556438
If this gets merged and considered as contribution here's the id on clueless tech

**Comment by RidhamRj** [comment]
image
@Debajyoti14 @Rajdip019 @nikhil25803 
pls see to this
kindly add hacktoberfest accepted label for approval

**Comment by Rajdip019** [comment]
Welcome. It takes some time. Thanks for contributing. @RidhamRj

**Pull request merged**
