### PR TITLE
added link of home page in footer logo and my data 

### PR DESCRIPTION
**Pull request by saugat-rimal**
Please merge it for hacktoberfest.

### CODE REVIEW

**Comment by Rajdip019** [comment]
This will be all counted as one PR. Is it ok for you? Or you can make two separate PR for data add and Adding link to Footer one. @saugat-rimal

**Comment by saugat-rimal** [comment]
i will make two seperate pr

**Comment by saugat-rimal** [comment]
okey

**Comment by saugat-rimal** [comment]
i have requested 2 pr. please merge it.

**Pull request closed without merging**
