### PR TITLE
Added my data

### PR DESCRIPTION
**Pull request by deedeecee**

### CODE REVIEW

**Comment by Rajdip019** [comment]
Please add your data outside contributors.unshift. @deedeecee

**Comment by deedeecee** [comment]
> Please add your data outside contributors.unshift. @deedeecee

Thanks for replying. Actually I'm not used to JavaScript programming. Can you please guide me on how should I proceed with your instruction? 
I got to know that unshift() method is used to add new elements to the beginning of the array. So, should I just use this method in contributors.js ?

**Comment by deedeecee** [comment]
@Debajyoti14 and @nikhil25803 yes, please!

**Comment by Rajdip019** [comment]
Good job @deedeecee 

Congrats 🎉, your PR got merged. To be eligible for the swags from ClueLess. Follow this steps.

Note that this repo is excluded from Hacktoberfest but this PR is still eligible for ClueLess Swags.

1. Star this repository. ⭐
2. SignIn / SignUp in [[ClueLess Website](https://www.clueless.tech/)](https://www.clueless.tech/) .
3. Go to profile section from the top right hand corner.



1. Comment your profile URL under this comment tagging the person who merged your PR.

That’s it. Follow the leaderboard !

And don’t forget to share your achievement with your friends.

**Comment by deedeecee** [comment]
@Rajdip019 Thanks a lot for merging my PR. Hacktoberfest was fun, learnt a lot from each one of the repositories. I will contribute more often 😄
Here is my Clueless Community Profile:
[Debankar Dutta Chowdhury](https://www.clueless.tech/profile/admin/76088949)

**Pull request merged**
