### PR TITLE
Added my data

### PR DESCRIPTION
**Pull request by bhavyasingh75**

### CODE REVIEW

**Comment by Rajdip019** [comment]
Please resolve the merge conflicts and update the PR. @bhavyasingh75

**Comment by bhavyasingh75** [comment]
> Please resolve the merge conflicts and update the PR. @bhavyasingh75

done.

**Comment by Rajdip019** [comment]
Hey you have added 91 lines. And also duplicated some of the contributor data. Please close this PR. Pull the latest form main add your data and make a new PR.  That would be easier. @bhavyasingh75

**Comment by bhavyasingh75** [comment]
> Hey you have added 91 lines. And also duplicated some of the contributor data. Please close this PR. Pull the latest form main add your data and make a new PR. That would be easier. @bhavyasingh75

could you please explain "duplicating contributor data" ? I was working by following the guidelines so I'm unaware about the 
thing that went wrong.

**Pull request closed without merging**
