### PR TITLE
Added my Data

### PR DESCRIPTION
**Pull request by jaydeepdey03**

### CODE REVIEW

**Comment by Rajdip019** [comment]
Please fix the merge conflicts and update the PR. @jaydeepdey03

**Comment by jaydeepdey03** [comment]
@Rajdip019 I've resolved the conflict. Kindly Check

Thanks

**Comment by Rajdip019** [comment]
Hey, please add the data in proper format read the docs. You are missing parenthesis. @jaydeepdey03

**Comment by Rajdip019** [comment]
Closing this PR, I guess one of your PR is merged for the same.

**Comment by Rajdip019** [comment]
Closing this PR, I guess one of your PR is merged for the same.

**Pull request closed without merging**
