### PR TITLE
HTML img tag to next/Image to fix issue #136

### PR DESCRIPTION
**Pull request by ramdhanihendrie**
I've changed the img tag to next/Image Components in CreatorSection.js and DiscordHome.js

Fix the issue #136

### CODE REVIEW

**Comment by Rajdip019** [comment]
Can you give a screenshot? how it looks after changing it from img tag to next/Image tag. @ramdhanihendrie

**Comment by ramdhanihendrie** [comment]
> Can you give a screenshot? how it looks after changing it from img tag to next/Image tag. @ramdhanihendrie


image-optimization
the load time of images was decreased

**Comment by Rajdip019** [comment]
Nice good job. Just resolve the conflicts and the PR is good to go! @ramdhanihendrie

**Comment by ramdhanihendrie** [comment]
Is there a problem with the PR? because the PR has not been merged

**Pull request closed without merging**
